#!/bin/bash

#SBATCH  --job-name=maces
#SBATCH  --nodes=1
##SBATCH  --ntasks-per-node=40
#SBATCH  --exclusive
#SBATCH  --time=02:00:00
#SBATCH  --partition=short
#SBATCH -A  esmd 
#SBATCH --mail-type=END
#SBATCH --mail-user=zeli.tan@pnnl.gov
#SBATCH --output=slurm.out
#SBATCH --error=slurm.out

module purge
module load intel netcdf/4.7.4 mvapich2

source activate /qfs/people/tanz151/.conda/envs/work_env

srun -n 1 python MACES_main.py -f namelist.maces.hunter_hydro.xml 

conda deactivate
